import type { Lang } from "@/lib/i18n";

export type LegalSection = { heading: string; body: string[] };
export type LegalDoc = { title: string; updated: string; sections: LegalSection[] };

type Dict = Record<Lang, LegalDoc>;

const TERMS: Dict = {
  en: {
    title: "Terms of Service",
    updated: "Last updated: September 2026",
    sections: [
      {
        heading: "1. General provisions",
        body: [
          "These Terms of Service govern your use of the CaseForge website — a platform for opening virtual CS2 cases, upgrading items and related entertainment features.",
          "By creating an account or using any part of the service you confirm that you have read, understood and accepted these Terms in full. If you do not agree, please stop using the site.",
        ],
      },
      {
        heading: "2. Age restriction (18+)",
        body: [
          "The service is strictly intended for users aged 18 or older (or the age of majority in your jurisdiction, whichever is higher).",
          "By signing in you confirm that you meet this requirement. We may suspend or delete accounts where there is reasonable doubt about the user's age.",
          "It is your responsibility to ensure that using this type of service is legal in your country of residence.",
        ],
      },
      {
        heading: "3. Account and Steam OpenID",
        body: [
          "Authentication is performed exclusively through Steam OpenID (Valve Corporation). We do not receive or store your Steam password — only the public profile data that Steam returns (SteamID, nickname, avatar).",
          "You are responsible for everything that happens under your account. Do not share access to your Steam account with third parties.",
          "You may be asked to provide a valid Steam trade link so that virtual items can be delivered to you.",
        ],
      },
      {
        heading: "4. Virtual items and balance",
        body: [
          "All items shown on the site are virtual in-game items. The on-site balance is a virtual unit of account used solely within the service.",
          "Case opening results are generated by a provably fair algorithm based on a hashed server seed and your client seed; the result cannot be predicted or changed after the round starts.",
          "Withdrawal of items is performed via Steam trade offers. We are not responsible for restrictions imposed by Valve (trade bans, holds, escrow).",
        ],
      },
      {
        heading: "5. Payments and cancellation policy",
        body: [
          "Balance top-ups are processed by third-party payment providers. By paying you confirm that you are the lawful owner of the payment method used.",
          "Because the service is digital content delivered instantly, completed top-ups and opened cases are final and non-refundable once the balance has been used, except where a refund is required by applicable law.",
          "If a payment was credited incorrectly due to a technical error, contact support on Telegram (https://t.me/dollar20trc) — verified errors are corrected or refunded.",
        ],
      },
      {
        heading: "6. Prohibited conduct",
        body: [
          "It is forbidden to exploit bugs, use multiple accounts, automate interactions (bots/scripts), launder funds or otherwise abuse the service.",
          "Violations may lead to confiscation of fraudulently obtained items, balance freeze and permanent account suspension without compensation.",
        ],
      },
      {
        heading: "7. Limitation of liability",
        body: [
          "The service is provided «as is» without warranties of any kind. We do not guarantee uninterrupted operation and are not liable for losses caused by force majeure, Valve platform changes or actions of third parties.",
          "Play responsibly. Opening cases is entertainment, not a way to earn money.",
        ],
      },
      {
        heading: "8. Changes to the Terms",
        body: [
          "We may update these Terms at any time. The current version is always available on this page; continued use of the service after changes means acceptance of the new version.",
        ],
      },
    ],
  },
  ru: {
    title: "Условия использования",
    updated: "Обновлено: сентябрь 2026",
    sections: [
      {
        heading: "1. Общие положения",
        body: [
          "Настоящие Условия использования регулируют работу сайта CaseForge — платформы для открытия виртуальных кейсов CS2, апгрейда предметов и связанных развлекательных функций.",
          "Создавая аккаунт или используя любую часть сервиса, вы подтверждаете, что прочитали, поняли и приняли эти Условия в полном объёме. Если вы не согласны — прекратите использование сайта.",
        ],
      },
      {
        heading: "2. Возрастное ограничение (18+)",
        body: [
          "Сервис предназначен строго для пользователей старше 18 лет (либо достигших совершеннолетия в вашей юрисдикции — применяется больший возраст).",
          "Входя на сайт, вы подтверждаете соответствие этому требованию. При обоснованных сомнениях в возрасте пользователя аккаунт может быть приостановлен или удалён.",
          "Вы самостоятельно отвечаете за то, чтобы использование подобного сервиса было законным в стране вашего проживания.",
        ],
      },
      {
        heading: "3. Аккаунт и Steam OpenID",
        body: [
          "Авторизация выполняется исключительно через Steam OpenID (Valve Corporation). Мы не получаем и не храним ваш пароль Steam — только публичные данные профиля, которые возвращает Steam (SteamID, никнейм, аватар).",
          "Вы несёте ответственность за все действия, совершённые под вашим аккаунтом. Не передавайте доступ к аккаунту Steam третьим лицам.",
          "Для выдачи виртуальных предметов может потребоваться действующая трейд-ссылка Steam.",
        ],
      },
      {
        heading: "4. Виртуальные предметы и баланс",
        body: [
          "Все предметы на сайте являются виртуальными игровыми предметами. Баланс на сайте — виртуальная расчётная единица, используемая только внутри сервиса.",
          "Результаты открытия кейсов формируются алгоритмом Provably Fair на основе хешированного серверного сида и вашего клиентского сида; результат невозможно предсказать или изменить после начала раунда.",
          "Вывод предметов осуществляется через трейд-офферы Steam. Мы не отвечаем за ограничения, вводимые Valve (трейд-баны, холды, escrow).",
        ],
      },
      {
        heading: "5. Платежи и политика отмены",
        body: [
          "Пополнение баланса обрабатывается сторонними платёжными провайдерами. Совершая платёж, вы подтверждаете, что являетесь законным владельцем используемого платёжного средства.",
          "Поскольку сервис является цифровым контентом с мгновенной доставкой, завершённые пополнения и открытые кейсы являются окончательными и не подлежат возврату после использования баланса, за исключением случаев, предусмотренных применимым законодательством.",
          "Если платёж был зачислен некорректно из-за технической ошибки — обратитесь в поддержку в Telegram (https://t.me/dollar20trc): подтверждённые ошибки исправляются или возмещаются.",
        ],
      },
      {
        heading: "6. Запрещённые действия",
        body: [
          "Запрещено использовать уязвимости и баги, создавать мультиаккаунты, автоматизировать действия (боты/скрипты), отмывать средства или иным образом злоупотреблять сервисом.",
          "Нарушения могут привести к изъятию нечестно полученных предметов, заморозке баланса и постоянной блокировке аккаунта без компенсации.",
        ],
      },
      {
        heading: "7. Ограничение ответственности",
        body: [
          "Сервис предоставляется «как есть», без каких-либо гарантий. Мы не гарантируем бесперебойную работу и не несём ответственности за убытки, вызванные форс-мажором, изменениями платформы Valve или действиями третьих лиц.",
          "Играйте ответственно. Открытие кейсов — развлечение, а не способ заработка.",
        ],
      },
      {
        heading: "8. Изменение условий",
        body: [
          "Мы можем обновлять настоящие Условия в любое время. Актуальная версия всегда доступна на этой странице; продолжение использования сервиса после изменений означает принятие новой редакции.",
        ],
      },
    ],
  },
  uk: {
    title: "Умови використання",
    updated: "Оновлено: вересень 2026",
    sections: [
      {
        heading: "1. Загальні положення",
        body: [
          "Ці Умови використання регулюють роботу сайту CaseForge — платформи для відкриття віртуальних кейсів CS2, апгрейду предметів та пов'язаних розважальних функцій.",
          "Створюючи акаунт або використовуючи будь-яку частину сервісу, ви підтверджуєте, що прочитали, зрозуміли та прийняли ці Умови в повному обсязі. Якщо ви не згодні — припиніть використання сайту.",
        ],
      },
      {
        heading: "2. Вікове обмеження (18+)",
        body: [
          "Сервіс призначений виключно для користувачів віком від 18 років (або повнолітніх у вашій юрисдикції — застосовується більший вік).",
          "Входячи на сайт, ви підтверджуєте відповідність цій вимозі. За наявності обґрунтованих сумнівів щодо віку користувача акаунт може бути призупинено або видалено.",
          "Ви самостійно відповідаєте за те, щоб використання подібного сервісу було законним у країні вашого проживання.",
        ],
      },
      {
        heading: "3. Акаунт і Steam OpenID",
        body: [
          "Авторизація виконується виключно через Steam OpenID (Valve Corporation). Ми не отримуємо і не зберігаємо ваш пароль Steam — лише публічні дані профілю, які повертає Steam (SteamID, нікнейм, аватар).",
          "Ви несете відповідальність за всі дії, вчинені під вашим акаунтом. Не передавайте доступ до акаунту Steam третім особам.",
          "Для видачі віртуальних предметів може знадобитися чинне трейд-посилання Steam.",
        ],
      },
      {
        heading: "4. Віртуальні предмети та баланс",
        body: [
          "Усі предмети на сайті є віртуальними ігровими предметами. Баланс на сайті — віртуальна розрахункова одиниця, що використовується лише всередині сервісу.",
          "Результати відкриття кейсів формуються алгоритмом Provably Fair на основі хешованого серверного сіда та вашого клієнтського сіда; результат неможливо передбачити або змінити після початку раунду.",
          "Виведення предметів здійснюється через трейд-офери Steam. Ми не відповідаємо за обмеження, що вводяться Valve (трейд-бани, холди, escrow).",
        ],
      },
      {
        heading: "5. Платежі та політика скасування",
        body: [
          "Поповнення балансу обробляється сторонніми платіжними провайдерами. Здійснюючи платіж, ви підтверджуєте, що є законним власником використаного платіжного засобу.",
          "Оскільки сервіс є цифровим контентом з миттєвою доставкою, завершені поповнення та відкриті кейси є остаточними і не підлягають поверненню після використання балансу, крім випадків, передбачених чинним законодавством.",
          "Якщо платіж було зараховано некоректно через технічну помилку — зверніться до підтримки в Telegram (https://t.me/dollar20trc): підтверджені помилки виправляються або відшкодовуються.",
        ],
      },
      {
        heading: "6. Заборонені дії",
        body: [
          "Заборонено використовувати вразливості та баги, створювати мультіакаунти, автоматизувати дії (боти/скрипти), відмивати кошти або іншим чином зловживати сервісом.",
          "Порушення можуть призвести до вилучення нечесно отриманих предметів, заморозки балансу та постійного блокування акаунта без компенсації.",
        ],
      },
      {
        heading: "7. Обмеження відповідальності",
        body: [
          "Сервіс надається «як є», без будь-яких гарантій. Ми не гарантуємо безперебійну роботу та не несемо відповідальності за збитки, спричинені форс-мажором, змінами платформи Valve або діями третіх осіб.",
          "Грайте відповідально. Відкриття кейсів — розвага, а не спосіб заробітку.",
        ],
      },
      {
        heading: "8. Зміна умов",
        body: [
          "Ми можемо оновлювати ці Умови будь-коли. Актуальна версія завжди доступна на цій сторінці; подальше використання сервісу після змін означає прийняття нової редакції.",
        ],
      },
    ],
  },
};

const PRIVACY: Dict = {
  en: {
    title: "Privacy Policy",
    updated: "Last updated: September 2026",
    sections: [
      {
        heading: "1. What data we collect",
        body: [
          "We collect the minimum data required for the service to work: your public Steam profile (SteamID64, nickname, avatar) returned by Steam OpenID, your trade link, game activity (opened cases, items, transactions) and technical data (IP address, browser, cookies).",
          "We never see or store your Steam password — authentication is performed on Valve's side.",
        ],
      },
      {
        heading: "2. How we use the data",
        body: [
          "The data is used to: identify your account, deliver virtual items via trade offers, process top-ups and withdrawals, provide provably fair game verification, prevent fraud and improve the service.",
          "We do not sell your personal data to third parties.",
        ],
      },
      {
        heading: "3. Third-party services",
        body: [
          "We rely on: Steam OpenID (Valve) for authentication, payment providers (e.g. CrystalPay) for processing payments, and hosting/analytics providers for infrastructure. Each of them processes data under their own privacy policies.",
        ],
      },
      {
        heading: "4. Data storage and security",
        body: [
          "Data is stored on protected servers and kept for as long as your account is active or as required by law. We apply technical and organizational measures to protect data from unauthorized access.",
          "No internet transmission is 100% secure; we cannot guarantee absolute security but promptly investigate any incident.",
        ],
      },
      {
        heading: "5. Your rights",
        body: [
          "You may request a copy of your data, its correction or deletion of your account by contacting support on Telegram: https://t.me/dollar20trc. Account deletion removes associated personal data except records we must keep for legal or anti-fraud purposes.",
        ],
      },
      {
        heading: "6. Age restriction",
        body: [
          "The service is not intended for persons under 18. We do not knowingly collect data of minors; such accounts are deleted upon discovery.",
        ],
      },
      {
        heading: "7. Changes to this Policy",
        body: [
          "We may update this Policy; the current version is always published on this page. Continued use of the service after changes constitutes acceptance.",
        ],
      },
    ],
  },
  ru: {
    title: "Политика конфиденциальности",
    updated: "Обновлено: сентябрь 2026",
    sections: [
      {
        heading: "1. Какие данные мы собираем",
        body: [
          "Мы собираем минимум данных, необходимых для работы сервиса: публичный профиль Steam (SteamID64, никнейм, аватар), возвращаемый Steam OpenID, вашу трейд-ссылку, игровую активность (открытые кейсы, предметы, транзакции) и технические данные (IP-адрес, браузер, cookie).",
          "Мы никогда не видим и не храним ваш пароль Steam — авторизация происходит на стороне Valve.",
        ],
      },
      {
        heading: "2. Как мы используем данные",
        body: [
          "Данные используются для: идентификации аккаунта, выдачи виртуальных предметов через трейд-офферы, обработки пополнений и выводов, проверки честности игр (Provably Fair), предотвращения мошенничества и улучшения сервиса.",
          "Мы не продаём ваши персональные данные третьим лицам.",
        ],
      },
      {
        heading: "3. Сторонние сервисы",
        body: [
          "Мы используем: Steam OpenID (Valve) для авторизации, платёжных провайдеров (например, CrystalPay) для обработки платежей, а также хостинг/аналитические сервисы для инфраструктуры. Каждый из них обрабатывает данные в соответствии со своей политикой конфиденциальности.",
        ],
      },
      {
        heading: "4. Хранение и защита данных",
        body: [
          "Данные хранятся на защищённых серверах в течение срока действия аккаунта либо срока, требуемого законом. Мы применяем технические и организационные меры для защиты данных от несанкционированного доступа.",
          "Ни одна передача данных в интернете не является абсолютно безопасной; мы не можем гарантировать стопроцентную защиту, но оперативно расследуем любые инциденты.",
        ],
      },
      {
        heading: "5. Ваши права",
        body: [
          "Вы можете запросить копию своих данных, их исправление или удаление аккаунта, обратившись в поддержку в Telegram: https://t.me/dollar20trc. Удаление аккаунта стирает связанные персональные данные, кроме записей, которые мы обязаны хранить по закону или в целях предотвращения мошенничества.",
        ],
      },
      {
        heading: "6. Возрастное ограничение",
        body: [
          "Сервис не предназначен для лиц младше 18 лет. Мы сознательно не собираем данные несовершеннолетних; такие аккаунты удаляются при обнаружении.",
        ],
      },
      {
        heading: "7. Изменения политики",
        body: [
          "Мы можем обновлять настоящую Политику; актуальная версия всегда опубликована на этой странице. Продолжение использования сервиса после изменений означает их принятие.",
        ],
      },
    ],
  },
  uk: {
    title: "Політика конфіденційності",
    updated: "Оновлено: вересень 2026",
    sections: [
      {
        heading: "1. Які дані ми збираємо",
        body: [
          "Ми збираємо мінімум даних, необхідних для роботи сервісу: публічний профіль Steam (SteamID64, нікнейм, аватар), який повертає Steam OpenID, ваше трейд-посилання, ігрову активність (відкриті кейси, предмети, транзакції) та технічні дані (IP-адреса, браузер, cookie).",
          "Ми ніколи не бачимо і не зберігаємо ваш пароль Steam — авторизація відбувається на боці Valve.",
        ],
      },
      {
        heading: "2. Як ми використовуємо дані",
        body: [
          "Дані використовуються для: ідентифікації акаунту, видачі віртуальних предметів через трейд-офери, обробки поповнень і виведень, перевірки чесності ігор (Provably Fair), запобігання шахрайству та покращення сервісу.",
          "Ми не продаємо ваші персональні дані третім особам.",
        ],
      },
      {
        heading: "3. Сторонні сервіси",
        body: [
          "Ми використовуємо: Steam OpenID (Valve) для авторизації, платіжних провайдерів (наприклад, CrystalPay) для обробки платежів, а також хостинг/аналітичні сервіси для інфраструктури. Кожен з них обробляє дані відповідно до власної політики конфіденційності.",
        ],
      },
      {
        heading: "4. Зберігання та захист даних",
        body: [
          "Дані зберігаються на захищених серверах протягом строку дії акаунту або строку, вимаганого законом. Ми застосовуємо технічні та організаційні заходи для захисту даних від несанкціонованого доступу.",
          "Жодна передача даних в інтернеті не є абсолютно безпечною; ми не можемо гарантувати стовідсотковий захист, але оперативно розслідуємо будь-які інциденти.",
        ],
      },
      {
        heading: "5. Ваші права",
        body: [
          "Ви можете запросити копію своїх даних, їхнє виправлення або видалення акаунту, звернувшись до підтримки в Telegram: https://t.me/dollar20trc. Видалення акаунту стирає пов'язані персональні дані, крім записів, які ми зобов'язані зберігати за законом або з метою запобігання шахрайству.",
        ],
      },
      {
        heading: "6. Вікове обмеження",
        body: [
          "Сервіс не призначений для осіб молодше 18 років. Ми свідомо не збираємо дані неповнолітніх; такі акаунти видаляються після виявлення.",
        ],
      },
      {
        heading: "7. Зміни політики",
        body: [
          "Ми можемо оновлювати цю Політику; актуальна версія завжди опублікована на цій сторінці. Подальше використання сервісу після змін означає їхнє прийняття.",
        ],
      },
    ],
  },
};

const COOKIES: Dict = {
  en: {
    title: "Cookie Policy",
    updated: "Last updated: September 2026",
    sections: [
      {
        heading: "1. What are cookies",
        body: [
          "Cookies are small text files stored on your device by the browser. We also use similar browser technologies (localStorage) to keep the site working and remember your preferences.",
        ],
      },
      {
        heading: "2. Which cookies we use",
        body: [
          "Strictly necessary: session and authentication data after signing in via Steam OpenID, security tokens. The site will not function without them.",
          "Functional: your interface language (ENG/RU/UA), saved trade link, chat and UI preferences.",
          "Analytical: aggregated, anonymized statistics about page visits that help us improve the service.",
        ],
      },
      {
        heading: "3. Third-party cookies",
        body: [
          "Payment providers (e.g. CrystalPay) and Steam may set their own cookies when you interact with their pages. Their use is governed by the policies of the respective companies.",
        ],
      },
      {
        heading: "4. Managing cookies",
        body: [
          "You can delete or block cookies in your browser settings at any time. Please note that blocking strictly necessary cookies will make sign-in and core features unavailable.",
          "By continuing to use the site you consent to the use of cookies as described in this Policy.",
        ],
      },
      {
        heading: "5. Changes",
        body: ["We may update this Policy; the current version is always available on this page."],
      },
    ],
  },
  ru: {
    title: "Политика cookie",
    updated: "Обновлено: сентябрь 2026",
    sections: [
      {
        heading: "1. Что такое cookie",
        body: [
          "Cookie — это небольшие текстовые файлы, которые браузер сохраняет на вашем устройстве. Мы также используем похожие технологии браузера (localStorage), чтобы сайт работал и запоминал ваши настройки.",
        ],
      },
      {
        heading: "2. Какие cookie мы используем",
        body: [
          "Строго необходимые: данные сессии и авторизации после входа через Steam OpenID, токены безопасности. Без них сайт не будет работать.",
          "Функциональные: выбранный язык интерфейса (ENG/RU/UA), сохранённая трейд-ссылка, настройки чата и интерфейса.",
          "Аналитические: обобщённая анонимная статистика посещений страниц, которая помогает улучшать сервис.",
        ],
      },
      {
        heading: "3. Сторонние cookie",
        body: [
          "Платёжные провайдеры (например, CrystalPay) и Steam могут устанавливать собственные cookie при взаимодействии с их страницами. Их использование регулируется политиками соответствующих компаний.",
        ],
      },
      {
        heading: "4. Управление cookie",
        body: [
          "Вы можете в любой момент удалить или заблокировать cookie в настройках браузера. Учтите: блокировка строго необходимых cookie сделает вход и основные функции недоступными.",
          "Продолжая использовать сайт, вы соглашаетесь с использованием cookie, описанным в настоящей Политике.",
        ],
      },
      {
        heading: "5. Изменения",
        body: [
          "Мы можем обновлять настоящую Политику; актуальная версия всегда доступна на этой странице.",
        ],
      },
    ],
  },
  uk: {
    title: "Політика cookie",
    updated: "Оновлено: вересень 2026",
    sections: [
      {
        heading: "1. Що таке cookie",
        body: [
          "Cookie — це невеликі текстові файли, які браузер зберігає на вашому пристрої. Ми також використовуємо подібні технології браузера (localStorage), щоб сайт працював і запам'ятовував ваші налаштування.",
        ],
      },
      {
        heading: "2. Які cookie ми використовуємо",
        body: [
          "Строго необхідні: дані сесії та авторизації після входу через Steam OpenID, токени безпеки. Без них сайт не працюватиме.",
          "Функціональні: обрана мова інтерфейсу (ENG/RU/UA), збережене трейд-посилання, налаштування чату та інтерфейсу.",
          "Аналітичні: узагальнена анонімна статистика відвідувань сторінок, яка допомагає покращувати сервіс.",
        ],
      },
      {
        heading: "3. Сторонні cookie",
        body: [
          "Платіжні провайдери (наприклад, CrystalPay) і Steam можуть встановлювати власні cookie під час взаємодії з їхніми сторінками. Їхнє використання регулюється політиками відповідних компаній.",
        ],
      },
      {
        heading: "4. Керування cookie",
        body: [
          "Ви можете будь-коли видалити або заблокувати cookie в налаштуваннях браузера. Зверніть увагу: блокування строго необхідних cookie зробить вхід та основні функції недоступними.",
          "Продовжуючи використовувати сайт, ви погоджуєтеся з використанням cookie, описаним у цій Політиці.",
        ],
      },
      {
        heading: "5. Зміни",
        body: [
          "Ми можемо оновлювати цю Політику; актуальна версія завжди доступна на цій сторінці.",
        ],
      },
    ],
  },
};

export const LEGAL_DOCS = { terms: TERMS, privacy: PRIVACY, cookies: COOKIES } as const;
export type LegalDocKey = keyof typeof LEGAL_DOCS;
