INSERT INTO public.items (slug,name,rarity,weapon,category,base_price) VALUES
('dual-berettas-heist','Dual Berettas | Heist','consumer','Dual Berettas','Pistols',0.06),
('aug-contractor','AUG | Contractor','consumer','AUG','Rifles',0.14),
('famas-palm','FAMAS | Palm','consumer','FAMAS','Rifles',0.16),
('ssg-08-green-ceramic','SSG 08 | Green Ceramic','consumer','SSG 08','Rifles',0.15),
('mag-7-storm','MAG-7 | Storm','consumer','MAG-7','Heavy',0.1),
('mp9-dizzy','MP9 | Dizzy','consumer','MP9','SMGs',0.13),
('p250-boreal-forest','P250 | Boreal Forest','consumer','P250','Pistols',0.16),
('scar-20-storm','SCAR-20 | Storm','consumer','SCAR-20','Rifles',0.15),
('pp-bizon-wood-block-camo','PP-Bizon | Wood Block Camo','consumer','PP-Bizon','SMGs',0.04),
('m249-jungle','M249 | Jungle','consumer','M249','Heavy',0.05),
('famas-vendetta','FAMAS | Vendetta','industrial','FAMAS','Rifles',0.54),
('ssg-08-carbon-fiber','SSG 08 | Carbon Fiber','industrial','SSG 08','Rifles',0.09),
('pp-bizon-traitor','PP-Bizon | Traitor','industrial','PP-Bizon','SMGs',0.08),
('p2000-marsh','P2000 | Marsh','industrial','P2000','Pistols',0.16),
('tec-9-rust-leaf','Tec-9 | Rust Leaf','industrial','Tec-9','Pistols',0.48),
('famas-calicamo','FAMAS | CaliCamo','industrial','FAMAS','Rifles',0.18),
('p90-wash-me','P90 | Wash me','industrial','P90','SMGs',0.6),
('p2000-granite-marbleized','P2000 | Granite Marbleized','industrial','P2000','Pistols',0.53),
('mac-10-palm','MAC-10 | Palm','industrial','MAC-10','SMGs',0.13),
('mac-10-silver','MAC-10 | Silver','industrial','MAC-10','SMGs',0.09),
('ump-45-oscillator','UMP-45 | Oscillator','milspec','UMP-45','SMGs',2.55),
('ump-45-metal-flowers','UMP-45 | Metal Flowers','milspec','UMP-45','SMGs',0.43),
('xm1014-irezumi','XM1014 | Irezumi','milspec','XM1014','Heavy',1.66),
('mp9-spy-prototype','MP9 | Spy Prototype','milspec','MP9','SMGs',0.41),
('xm1014-varicamo-blue','XM1014 | VariCamo Blue','milspec','XM1014','Heavy',1.26),
('mp9-modest-threat','MP9 | Modest Threat','milspec','MP9','SMGs',0.44),
('tec-9-cracked-opal','Tec-9 | Cracked Opal','milspec','Tec-9','Pistols',0.72),
('cz75-auto-twist','CZ75-Auto | Twist','milspec','CZ75-Auto','Pistols',0.47),
('famas-2a2f','FAMAS | 2A2F','milspec','FAMAS','Rifles',2.2),
('scar-20-wild-berry','SCAR-20 | Wild Berry','milspec','SCAR-20','Rifles',0.49),
('r8-revolver-survivalist','R8 Revolver | Survivalist','milspec','R8 Revolver','Pistols',1.39),
('sawed-off-origami','Sawed-Off | Origami','milspec','Sawed-Off','Heavy',1.35),
('mp9-dark-age','MP9 | Dark Age','milspec','MP9','SMGs',1.56),
('mp5-sd-focus','MP5-SD | Focus','milspec','MP5-SD','SMGs',0.8),
('xm1014-teclu-burner','XM1014 | Teclu Burner','restricted','XM1014','Heavy',4.81),
('dual-berettas-demolition','Dual Berettas | Demolition','restricted','Dual Berettas','Pistols',1.27),
('mp7-amberline','MP7 | Amberline','restricted','MP7','SMGs',6.65),
('cz75-auto-slalom','CZ75-Auto | Slalom','restricted','CZ75-Auto','Pistols',1.51),
('pp-bizon-blue-streak','PP-Bizon | Blue Streak','restricted','PP-Bizon','SMGs',5.51),
('mp7-fade','MP7 | Fade','restricted','MP7','SMGs',8.72),
('five-seven-heat-treated','Five-SeveN | Heat Treated','restricted','Five-SeveN','Pistols',5.13),
('nova-baroque-orange','Nova | Baroque Orange','restricted','Nova','Heavy',2.11),
('cz75-auto-tread-plate','CZ75-Auto | Tread Plate','restricted','CZ75-Auto','Pistols',9.9),
('p90-chopper','P90 | Chopper','restricted','P90','SMGs',2.32),
('glock-18-umbral-rabbit','Glock-18 | Umbral Rabbit','restricted','Glock-18','Pistols',1.22),
('cz75-auto-tigris','CZ75-Auto | Tigris','restricted','CZ75-Auto','Pistols',9.31),
('desert-eagle-firebreathing','Desert Eagle | Firebreathing','restricted','Desert Eagle','Pistols',6.54),
('mag-7-praetorian','MAG-7 | Praetorian','restricted','MAG-7','Heavy',1.64),
('ak-47-redline','AK-47 | Redline','classified','AK-47','Rifles',59.06),
('aug-lil-pig','AUG | Lil'' Pig','classified','AUG','Rifles',5.75),
('m4a1-s-master-piece','M4A1-S | Master Piece','classified','M4A1-S','Rifles',5.55),
('nova-hyper-beast','Nova | Hyper Beast','classified','Nova','Heavy',9.77),
('awp-green-energy','AWP | Green Energy','classified','AWP','Rifles',57.66),
('usp-s-serum','USP-S | Serum','classified','USP-S','Pistols',5.63),
('ump-45-primal-saber','UMP-45 | Primal Saber','classified','UMP-45','SMGs',24.9),
('ump-45-wild-child','UMP-45 | Wild Child','classified','UMP-45','SMGs',4.66),
('negev-mj-lnir','Negev | Mjölnir','classified','Negev','Heavy',7.73),
('mp7-abyssal-apparition','MP7 | Abyssal Apparition','classified','MP7','SMGs',20.95),
('p90-nostalgia','P90 | Nostalgia','classified','P90','SMGs',59.92),
('desert-eagle-starcade','Desert Eagle | Starcade','classified','Desert Eagle','Pistols',39.37),
('p90-cold-blooded','P90 | Cold Blooded','classified','P90','SMGs',9.81),
('sawed-off-devourer','Sawed-Off | Devourer','classified','Sawed-Off','Heavy',4.06),
('m4a4-buzz-kill','M4A4 | Buzz Kill','covert','M4A4','Rifles',185.16),
('shadow-daggers-forest-ddpat','★ Shadow Daggers | Forest DDPAT','covert','Shadow Daggers','Knives',30.33),
('shadow-daggers-night','★ Shadow Daggers | Night','covert','Shadow Daggers','Knives',16.42),
('navaja-knife-boreal-forest','★ Navaja Knife | Boreal Forest','covert','Navaja Knife','Knives',30.07),
('survival-knife-slaughter','★ Survival Knife | Slaughter','covert','Survival Knife','Knives',23.32),
('survival-knife-tiger-tooth','★ Survival Knife | Tiger Tooth','covert','Survival Knife','Knives',35.51),
('navaja-knife-crimson-web','★ Navaja Knife | Crimson Web','covert','Navaja Knife','Knives',205.12),
('famas-bad-trip','FAMAS | Bad Trip','covert','FAMAS','Rifles',117.83),
('paracord-knife-urban-masked','★ Paracord Knife | Urban Masked','covert','Paracord Knife','Knives',35.62),
('karambit-forest-ddpat','★ Karambit | Forest DDPAT','covert','Karambit','Knives',134.76),
('flip-knife-rust-coat','★ Flip Knife | Rust Coat','covert','Flip Knife','Knives',16.26),
('falchion-knife-slaughter','★ Falchion Knife | Slaughter','covert','Falchion Knife','Knives',30.08),
('talon-knife-scorched','★ Talon Knife | Scorched','covert','Talon Knife','Knives',287.22),
('huntsman-knife-bright-water','★ Huntsman Knife | Bright Water','covert','Huntsman Knife','Knives',48.09),
('flip-knife','★ Flip Knife','covert','Flip Knife','Knives',165.28),
('butterfly-knife-doppler','★ Butterfly Knife | Doppler','covert','Butterfly Knife','Knives',46.71),
('sport-gloves-scarlet-shamagh','★ Sport Gloves | Scarlet Shamagh','exotic','Sport Gloves','Gloves',856.54),
('hand-wraps-arboreal','★ Hand Wraps | Arboreal','exotic','Hand Wraps','Gloves',244.03),
('moto-gloves-eclipse','★ Moto Gloves | Eclipse','exotic','Moto Gloves','Gloves',148.8),
('sport-gloves-arid','★ Sport Gloves | Arid','exotic','Sport Gloves','Gloves',581.07),
('hand-wraps-leather','★ Hand Wraps | Leather','exotic','Hand Wraps','Gloves',469.22),
('bloodhound-gloves-guerrilla','★ Bloodhound Gloves | Guerrilla','exotic','Bloodhound Gloves','Gloves',158.98),
('hand-wraps-cobalt-skulls','★ Hand Wraps | Cobalt Skulls','exotic','Hand Wraps','Gloves',111.57),
('sport-gloves-violet-beadwork','★ Sport Gloves | Violet Beadwork','exotic','Sport Gloves','Gloves',788.5),
('sport-gloves-blaze','★ Sport Gloves | Blaze','exotic','Sport Gloves','Gloves',1881.63),
('driver-gloves-queen-jaguar','★ Driver Gloves | Queen Jaguar','exotic','Driver Gloves','Gloves',563.76),
('driver-gloves-racing-green','★ Driver Gloves | Racing Green','exotic','Driver Gloves','Gloves',120.19),
('sport-gloves-hedge-maze','★ Sport Gloves | Hedge Maze','exotic','Sport Gloves','Gloves',859.14),
('m4a4-howl','M4A4 | Howl','contraband','M4A4','Rifles',2238.49)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.cases (slug,name,category,price,tag,is_active) VALUES
('starter-case','Starter Case','Budget',0.75,'NEW',true),
('street-ops','Street Ops Case','Budget',1.99,NULL,true),
('neon-riot','Neon Riot Case','Covered',4.99,'HOT',true),
('covert-vault','Covert Vault','Covered',14.99,NULL,true),
('blade-runner','Blade Runner','Knives',34.99,NULL,true),
('golden-hands','Golden Hands','Gloves',59.99,NULL,true),
('high-roller','High Roller','Custom',249.99,'VIP',true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.case_items (case_id,item_id,weight)
SELECT c.id,i.id,v.w FROM (VALUES
('starter-case','mag-7-storm',900),('starter-case','famas-palm',900),('starter-case','mp9-dizzy',900),('starter-case','p250-boreal-forest',900),('starter-case','dual-berettas-heist',900),('starter-case','famas-calicamo',600),('starter-case','p90-wash-me',600),('starter-case','famas-vendetta',600),('starter-case','mac-10-palm',600),('starter-case','pp-bizon-traitor',600),('starter-case','mp9-dark-age',360),('starter-case','xm1014-irezumi',360),('starter-case','r8-revolver-survivalist',360),('starter-case','tec-9-cracked-opal',360),('starter-case','mp9-spy-prototype',360),('starter-case','desert-eagle-firebreathing',110),('starter-case','pp-bizon-blue-streak',110),('starter-case','dual-berettas-demolition',110),('starter-case','mp7-amberline',110),('starter-case','cz75-auto-tigris',110),('starter-case','nova-hyper-beast',26),('starter-case','mp7-abyssal-apparition',26),('starter-case','p90-cold-blooded',26),('starter-case','negev-mj-lnir',26),('starter-case','awp-green-energy',26),('starter-case','survival-knife-slaughter',4),('starter-case','talon-knife-scorched',4),('starter-case','m4a4-buzz-kill',4),('starter-case','butterfly-knife-doppler',4),('starter-case','flip-knife-rust-coat',4),
('street-ops','pp-bizon-traitor',760),('street-ops','mac-10-silver',760),('street-ops','famas-calicamo',760),('street-ops','p2000-granite-marbleized',760),('street-ops','p90-wash-me',760),('street-ops','famas-2a2f',720),('street-ops','ump-45-metal-flowers',720),('street-ops','xm1014-irezumi',720),('street-ops','mp9-dark-age',720),('street-ops','xm1014-varicamo-blue',720),('street-ops','xm1014-teclu-burner',380),('street-ops','mp7-fade',380),('street-ops','mp7-amberline',380),('street-ops','dual-berettas-demolition',380),('street-ops','cz75-auto-slalom',380),('street-ops','ump-45-wild-child',110),('street-ops','awp-green-energy',110),('street-ops','ump-45-primal-saber',110),('street-ops','usp-s-serum',110),('street-ops','p90-nostalgia',110),('street-ops','navaja-knife-boreal-forest',28),('street-ops','m4a4-buzz-kill',28),('street-ops','talon-knife-scorched',28),('street-ops','butterfly-knife-doppler',28),('street-ops','navaja-knife-crimson-web',28),('street-ops','hand-wraps-leather',2),('street-ops','sport-gloves-violet-beadwork',2),('street-ops','hand-wraps-arboreal',2),('street-ops','sport-gloves-arid',2),('street-ops','moto-gloves-eclipse',2),
('neon-riot','ump-45-metal-flowers',840),('neon-riot','famas-2a2f',840),('neon-riot','ump-45-oscillator',840),('neon-riot','tec-9-cracked-opal',840),('neon-riot','xm1014-irezumi',840),('neon-riot','pp-bizon-blue-streak',700),('neon-riot','mp7-fade',700),('neon-riot','dual-berettas-demolition',700),('neon-riot','five-seven-heat-treated',700),('neon-riot','nova-baroque-orange',700),('neon-riot','ump-45-wild-child',320),('neon-riot','aug-lil-pig',320),('neon-riot','ump-45-primal-saber',320),('neon-riot','mp7-abyssal-apparition',320),('neon-riot','negev-mj-lnir',320),('neon-riot','navaja-knife-boreal-forest',130),('neon-riot','m4a4-buzz-kill',130),('neon-riot','karambit-forest-ddpat',130),('neon-riot','falchion-knife-slaughter',130),('neon-riot','survival-knife-tiger-tooth',130),('neon-riot','hand-wraps-leather',10),('neon-riot','bloodhound-gloves-guerrilla',10),('neon-riot','sport-gloves-blaze',10),('neon-riot','driver-gloves-queen-jaguar',10),('neon-riot','moto-gloves-eclipse',10),
('covert-vault','pp-bizon-blue-streak',780),('covert-vault','mp7-fade',780),('covert-vault','cz75-auto-tread-plate',780),('covert-vault','cz75-auto-slalom',780),('covert-vault','mag-7-praetorian',780),('covert-vault','negev-mj-lnir',680),('covert-vault','m4a1-s-master-piece',680),('covert-vault','mp7-abyssal-apparition',680),('covert-vault','p90-cold-blooded',680),('covert-vault','ak-47-redline',680),('covert-vault','paracord-knife-urban-masked',460),('covert-vault','shadow-daggers-forest-ddpat',460),('covert-vault','karambit-forest-ddpat',460),('covert-vault','flip-knife',460),('covert-vault','falchion-knife-slaughter',460),('covert-vault','sport-gloves-hedge-maze',80),('covert-vault','sport-gloves-blaze',80),('covert-vault','moto-gloves-eclipse',80),('covert-vault','hand-wraps-arboreal',80),('covert-vault','driver-gloves-queen-jaguar',80),
('blade-runner','ak-47-redline',720),('blade-runner','sawed-off-devourer',720),('blade-runner','p90-cold-blooded',720),('blade-runner','negev-mj-lnir',720),('blade-runner','awp-green-energy',720),('blade-runner','navaja-knife-boreal-forest',880),('blade-runner','huntsman-knife-bright-water',880),('blade-runner','navaja-knife-crimson-web',880),('blade-runner','paracord-knife-urban-masked',880),('blade-runner','karambit-forest-ddpat',880),('blade-runner','bloodhound-gloves-guerrilla',400),('blade-runner','hand-wraps-cobalt-skulls',400),('blade-runner','hand-wraps-leather',400),('blade-runner','moto-gloves-eclipse',400),('blade-runner','sport-gloves-violet-beadwork',400),
('golden-hands','flip-knife',1040),('golden-hands','huntsman-knife-bright-water',1040),('golden-hands','falchion-knife-slaughter',1040),('golden-hands','survival-knife-tiger-tooth',1040),('golden-hands','shadow-daggers-night',1040),('golden-hands','sport-gloves-arid',960),('golden-hands','driver-gloves-racing-green',960),('golden-hands','moto-gloves-eclipse',960),('golden-hands','sport-gloves-scarlet-shamagh',960),('golden-hands','sport-gloves-hedge-maze',960),
('high-roller','navaja-knife-boreal-forest',800),('high-roller','famas-bad-trip',800),('high-roller','huntsman-knife-bright-water',800),('high-roller','flip-knife-rust-coat',800),('high-roller','flip-knife',800),('high-roller','sport-gloves-hedge-maze',1180),('high-roller','sport-gloves-arid',1180),('high-roller','sport-gloves-blaze',1180),('high-roller','driver-gloves-queen-jaguar',1180),('high-roller','sport-gloves-scarlet-shamagh',1180),('high-roller','m4a4-howl',100)
) AS v(cs,it,w) JOIN public.cases c ON c.slug=v.cs JOIN public.items i ON i.slug=v.it
ON CONFLICT DO NOTHING;