// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

/**
 * Always resolve a fresh access token right before the RPC leaves the browser.
 * A token that is missing or about to expire is refreshed first, so protected
 * server functions never answer "Unauthorized: No authorization header".
 */
export async function getAccessToken(): Promise<string | null> {
  const { data } = await supabase.auth.getSession()
  const session = data.session
  if (!session) {
    const { data: refreshed } = await supabase.auth.refreshSession()
    return refreshed.session?.access_token ?? null
  }

  const expiresAt = session.expires_at ? session.expires_at * 1000 : 0
  const nearlyExpired = expiresAt > 0 && expiresAt - Date.now() < 60_000
  if (!session.access_token || nearlyExpired) {
    const { data: refreshed } = await supabase.auth.refreshSession()
    return refreshed.session?.access_token ?? session.access_token ?? null
  }
  return session.access_token
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | null = null
    try {
      token = await getAccessToken()
    } catch {
      token = null
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
