// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


export class MissingSupabaseConfigError extends Error {
  readonly missing: string[];

  constructor(missing: string[]) {
    super(
      `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect your Supabase project to continue.`,
    );
    this.name = 'MissingSupabaseConfigError';
    this.missing = missing;
  }
}

const DEFAULT_SUPABASE_URL = 'https://hpbjxknfyexhfwktnpyb.supabase.co';

function readServerEnv(name: string): string | undefined {
  return typeof process === 'undefined' ? undefined : process.env[name];
}

export function getSupabaseConfig():
  | { ok: true; url: string; key: string }
  | { ok: false; missing: string[] } {
  // VITE_* is read first in the browser. SUPABASE_* remains available for SSR.
  const url =
    import.meta.env['VITE_SUPABASE_URL'] || readServerEnv('SUPABASE_URL') || DEFAULT_SUPABASE_URL;
  const key =
    readServerEnv('SUPABASE_ANON_KEY') ||
    import.meta.env['VITE_SUPABASE_ANON_KEY'] ||
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    readServerEnv('SUPABASE_PUBLISHABLE_KEY');

  if (!key) {
    return {
      ok: false,
      missing: ['SUPABASE_ANON_KEY'],
    };
  }

  return { ok: true, url, key };
}

function createSupabaseClient() {
  const config = getSupabaseConfig();
  if (!config.ok) {
    const error = new MissingSupabaseConfigError(config.missing);
    console.error(`[Supabase] ${error.message}`);
    throw error;
  }

  return createClient<Database>(config.url, config.key, {
    global: {
      fetch: createSupabaseFetch(config.key),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

